# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


joint_controller_ur1:
  type: "position_controllers/JointPositionController"
  joint: shoulder_pan_joint
  pid: {p: 40.0, i: 0.01, d: 1.0}

joint_controller_ur2:
  type: "position_controllers/JointPositionController"
  joint: shoulder_lift_joint
  pid: {p: 40.0, i: 0.01, d: 1.0}

joint_controller_ur3:
  type: "position_controllers/JointPositionController"
  joint: elbow_joint
  pid: {p: 40.0, i: 0.01, d: 1.0}

joint_controller_ur4:
  type: "position_controllers/JointPositionController"
  joint: wrist_1_joint
  pid: {p: 40.0, i: 0.01, d: 1.0}

joint_controller_ur5:
  type: "position_controllers/JointPositionController"
  joint: wrist_2_joint
  pid: {p: 40.0, i: 0.01, d: 1.0}

joint_controller_ur6:
  type: "position_controllers/JointPositionController"
  joint: wrist_3_joint
  pid: {p: 40.0, i: 0.01, d: 1.0}
